### PR TITLE
Port to Multi-Loader(Add Fabric/Quilt Support) 1.18.2

### PR DESCRIPTION
**Pull request by CorgiTaco**
WIP, at the time of writing heavily incomplete and ~~broken~~

### CODE REVIEW

**Comment by CorgiTaco** [comment]
BAHAHA I think there's a better way to not do this god awful nightmare...

**Comment by CorgiTaco** [comment]
Ok looked over what is possible, seems like it's not possible to have geckolib deobfuscated as a dependency in the common module, so for now we'll need to do the abstract entity classes in common and implement them respectively in each mod loader

**Comment by ghost** [comment]
The entities can be implemented within the common; Regardless of Forge and Fabric since they only need the interface (and obvs what the interface uses) from https://github.com/bernie-g/geckolib-core. You could also easily make a facade for anything client side (The actual renderers and models) since they're needed from the actual geckolib. Or make a build of geckolib that works with de-obfuscating in mojmap for Fabric.

**Comment by ghost** [comment]
Additionally, bringing back up, I have started a complete overhaul of GeckoLib Core (And plan to do an overhaul of GeckoLib) https://github.com/chaottic/geckolib-core If you'd like to contribute to it: to make it more friendly for the development of Features and Creatures, you are more than welcome.

**Pull request closed without merging**
